[package]
name = "agre-cli-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
agre-core = { version = "0.1.0", path = "../../crates/agre-core" }
agre-llm = { version = "0.1.0", path = "../../crates/agre-llm" }
agre-runtime = { version = "0.1.0", path = "../../crates/agre-runtime" }
agre-tools = { version = "0.1.0", path = "../../crates/agre-tools" }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
dotenvy = { workspace = true }
tokio = { workspace = true, features = ["full"] }
