[package]
name = "agre-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
agre-core = { version = "0.1.0", path = "../../crates/agre-core" }
agre-llm = { version = "0.1.0", path = "../../crates/agre-llm" }
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
